# Generated by Django 3.1.7 on 2021-11-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
